"""
EchoSim – FastAPI entrypoint
Serves:
  • Static assets (GIF/JPG/SVG) at /static/*
  • All API routes in routes.py
  • Hand-written OpenAPI spec at /openapi.json
"""

from pathlib import Path
import json

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from routes import router  # your existing endpoints

# --------------------------------------------------------------------------- #
# Paths & constants
# --------------------------------------------------------------------------- #

BASE_DIR   = Path(__file__).resolve().parent
STATIC_DIR = BASE_DIR / "static"         # store all GIF/JPG/SVG here
STATIC_DIR.mkdir(exist_ok=True)          # auto-create if missing

# --------------------------------------------------------------------------- #
# FastAPI app
# --------------------------------------------------------------------------- #

app = FastAPI(
    title="EchoSim",
    description="Heart-failure narrative simulation with gamified learning",
    version="3.2.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# 1️⃣  Static assets  -------------------------------------------------------- #

# URL → https://<host>/static/<filename>.gif
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")

# 2️⃣  API routes  ----------------------------------------------------------- #

app.include_router(router)

# 3️⃣  Hand-written OpenAPI  -------------------------------------------------- #

@app.get("/openapi.json", include_in_schema=False)
def custom_spec():
    """Return the repo’s pre-baked OpenAPI schema instead of autogenerated one."""
    return json.loads((BASE_DIR / "openapi_schema.json").read_text())

# 4️⃣  Friendly root endpoint  ---------------------------------------------- #

@app.get("/", include_in_schema=False)
def root():
    return {"detail": "EchoSim flat-repo server running"}

